config/routes.rb
Rails.application.routes.draw do
  get '/plugs', to: 'plugs#index', as: :'plug'
  resources :topics do
    member do
      post 'downvote'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/users/:id', to: 'users#profile', as: 'user'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "topics#index"
  get 'search', to: 'search#index'
  get '/service-worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  include Pagy::Backend

  def index
    @query = Topic.search(params[:query])
    @pagy, @topics = pagy(@query)
  end
end

app/views/search/_form.html.erb
<%= form_tag(search_path, method: :get, data: { turbo_frame: :search_results, turbo_action: "advance" }) do %>
  <%= text_field_tag :query, params[:query],
    type: "search",
    placeholder: "Search",
    class: "lg:w-80 w-full border border-gray-300 rounded-full px-2 py-2 outline-none focus:border-gray-200 focus:ring-gray-200",
    oninput: "this.form.requestSubmit()" %>
<% end %>

app/views/search/index.html.erb
<% content_for :title, "Search results" %>

<%= turbo_frame_tag :search_results do %>
  <h1 class="text-4xl mb-4 pb-4 text-gray-800">
    Search results
    <% if params[:query].present? %>
      for <span class='font-semibold'>"<%= "#{params[:query]}" %>"</span>
    <% end %>
  </h1>

  <% if @topics.present? %>
    <h2 class="text-3xl mt-8 mb-2 font-semibold text-gray-800">
      <%= render "shared/topic_count", topics: @query %>
    </h2>
    
    <%= turbo_frame_tag "topics_#{@pagy.page}" do %>
      <%= render partial: "topics/topic", collection: @topics, cached: true %>
      <% unless @pagy.page == @pagy.pages %>
        <%= turbo_frame_tag "topics_#{@pagy.next}", src: topics_path(page: @pagy.next), loading: "lazy" do %>
          <%= render "shared/loader" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>