config/routes.rb
Rails.application.routes.draw do
  get '/plugs', to: 'plugs#index', as: :'plug'
  resources :topics do
    member do
      post 'downvote'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/users/:id', to: 'users#profile', as: 'user'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "topics#index"
  get 'search', to: 'search#index'
  get '/service-worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  extend FriendlyId
  include FriendlyIdGenerator

  belongs_to :user, touch: true

  validates :title, :hashtag, :x_link, presence: true
  validates :hashtag, format: { without: /\A#/, message: I18n.t('topics.validations.hashtag') }
  validates_with TweetUrlValidator, fields: [:x_link]

  before_validation :remove_query_string

  broadcasts_refreshes

  friendly_id :title, use: %i[slugged history], slug_generator_class: ReusableSlugGenerator

  def should_generate_new_friendly_id?
    title_changed?
  end

  def self.search(query)
    where('title ILIKE :query OR hashtag ILIKE :query OR x_link ILIKE :query', query: "%#{query}%")
  end

  serialize :downvoted_user_ids, type: Array, coder: JSON

  def downvote!(user)
    if user_has_downvoted?(user)
      update(downvotes: downvotes - 1, downvoted_user_ids: downvoted_user_ids - [user.id])
    else
      update(downvotes: downvotes + 1, downvoted_user_ids: downvoted_user_ids << user.id)
    end
  end

  def user_has_downvoted?(user)
    downvoted_user_ids.include?(user.id)
  end

  private

  def remove_query_string
    return if x_link.blank?

    uri = URI.parse(x_link)
    uri.query = nil
    self.x_link = uri
  end
end
# == Schema Information
#
# Table name: topics
#
#  id                 :bigint           not null, primary key
#  downvoted_user_ids :text
#  downvotes          :integer          default(0), not null
#  hashtag            :string           not null
#  slug               :string
#  title              :string           not null
#  x_link             :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint           not null
#
# Indexes
#
#  index_topics_on_slug     (slug) UNIQUE
#  index_topics_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  include Pagy::Backend

  before_action :set_topic, only: %i[show edit update destroy downvote]
  before_action :authenticate_user!, only: %i[new downvote]

  def index
    @pagy, @topics = pagy(Topic.includes(:user).where(id: topic_ids).order(created_at: :desc))
  end

  def show; end

  def new
    @topic = Topic.new
    @autofocus = true
  end

  def edit
    @autofocus = false
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      clear_cache
      redirect_to @topic, notice: t('topics.saved')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_url(@topic), notice: t('topics.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topic.destroy!
    redirect_to topics_url, notice: t('topics.deleted')
  end

  def downvote
    @topic.downvote!(current_user)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(
            "topic_#{@topic.id}_downvote_counter",
            partial: 'topics/downvote_counter',
            locals: { counter: @topic.downvotes, topic: @topic }
          )
        ]
      end
    end
  end

  private

  def set_topic
    @topic = Topic.includes(:user).friendly.find(params[:id])
    return unless params[:id] != @topic.slug

    redirect_to @topic, status: :moved_permanently
  end

  def topic_params
    params.require(:topic).permit(:title, :x_link, :hashtag, :user_id)
  end

  def topic_ids
    Rails.cache.fetch('topic_ids') do
      Topic.pluck(:id)
    end
  end

  def clear_cache
    Rails.cache.delete('topic_ids')
  end
end

app/views/topics/_downvote_counter.erb
<%= turbo_frame_tag "topic_#{topic.id}_downvote_counter" do %>
  <%= button_to downvote_topic_path(topic), method: :post, class: "py-2 px-0 mr-1" do %>
    <div class="flex items-center">
      <% cache("bx-downvote.svg") do %>
        <%= image_tag "bx-downvote.svg", alt: "Downvote", draggable: false %>
      <% end %>
      <span class="text-sm">
        <%= topic.user_has_downvoted?(current_user) ? '+' : '' %>
        <%= "#{format_count(counter) if counter > 0}" %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/topics/_form.html.erb
<%= form_with(model: topic, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.label :title do %>
      Title <span class="text-red-500">*</span>
    <% end %>
    <%= form.text_field :title, placeholder: "Topic title", autofocus: @autofocus, class: "rounded-lg block border border-gray-300 focus:outline-none focus:border-black focus:ring-black px-3 py-2 mt-2 w-full" %>
    <%= render "shared/form_error", topic: topic, field: :title %>
  </div>

  <div class="my-5">
    <%= form.label :x_link do %>
      X link <span class="text-red-500">*</span>
    <% end %>
    <%= form.text_field :x_link, placeholder: "Link to relevant X post", class: "rounded-lg block border border-gray-300 focus:border-black focus:ring-black focus:outline-none px-3 py-2 mt-2 w-full" %>
    <%= render "shared/form_error", topic: topic, field: :x_link %>
  </div>

  <div class="my-5">
    <%= form.label :hashtag do %>
      Hashtag <span class="text-red-500">*</span>
    <% end %>
    <%= form.text_field :hashtag, placeholder: "Hashtag without '#'", class: "rounded-lg block border border-gray-300 focus:border-black focus:ring-black focus:outline-none px-3 py-2 mt-2 w-full" %>
    <%= render "shared/form_error", topic: topic, field: :hashtag %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-black text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<%= turbo_stream_from topic %>

<div id="<%= dom_id topic %>" class="max-w-xl">
  <h1 class="mt-5 <%= action_name == 'show' ? 'text-4xl' : 'text-3xl' %>">
    <% if action_name == 'show' %>
      <%= topic.title %>
    <% else %>
      <%= link_to topic, class: 'hover:underline', data: { turbo_frame: '_top' } do %>
        <%= topic.title %>
      <% end %>
    <% end %>
  </h1>

  <p class="mt-2 text-gray-500 text-sm">
    <%= link_to user_path(topic.user), data: { turbo_frame: "_top" } do %>
      <%= topic.user.username %>
    <% end %>
    <%= posted_on(topic.created_at) %>
  </p>

  <%= embed_tweet(topic.x_link) %>

  <p class="my-4 text-gray-600 text-xl">
    #<%= topic.hashtag %>
  </p>

  <% if action_name != "show" %>
    <div class="flex">
      <% if user_signed_in? %>
        <%= render "topics/downvote_counter", counter: topic.downvotes, topic: topic %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<% content_for :title, "Edit topic" %>

<div class="mx-auto md:w-2/3 w-full w-full max-w-md">
  <h1 class="font-bold text-4xl">Editing topic</h1>

  <%= render "form", topic: @topic %>

  <%= link_to "View topic", @topic,
    class: "rounded-lg ml-2 py-3 px-5 text-gray-500 border border-gray-500 inline-block font-medium focus:outline-none" %>
</div>

app/views/topics/index.html.erb
<% if @topics.present? %>
  <%= turbo_frame_tag "topics_#{@pagy.page}" do %>
    <%= render partial: "topic", collection: @topics, cached: true %>
    <% unless @pagy.page == @pagy.pages %>
      <%= turbo_frame_tag "topics_#{@pagy.next}", src: topics_path(page: @pagy.next), loading: "lazy" do %>
        <%= render "shared/loader" %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%= render 'shared/empty_state', message: "Be the first to confirm a topic." %>
<% end %>

app/views/topics/new.html.erb
<% content_for :title, "New topic" %>

<div class="mx-auto md:w-2/3 w-full w-full max-w-md">
  <h1 class="font-bold text-4xl">New topic</h1>

  <%= render "form", topic: @topic %>
</div>

app/views/topics/show.html.erb
<% content_for :title, @topic.title %>

<%= render @topic %>

<div class="flex items-center lg:justify-start justify-center">
  <% if user_topics(@topic) %>
    <%= link_to "Edit topic", edit_topic_path(@topic),
      class: "rounded-lg py-2 mr-3 px-4 ml-2 text-gray-500 border border-gray-500 hover:bg-gray-100 inline-block font-medium focus:outline-none" %>
    <%= button_to "Delete topic", topic_path(@topic),
      method: :delete, data: { turbo_confirm: "Delete topic?" },
      class: "rounded-lg py-2 px-4 text-red-500 border border-red-500 hover:bg-red-100 font-medium focus:outline-none" %>
  <% else %>
    <% if user_signed_in? %>
      <%= render "topics/downvote_counter", counter: @topic.downvotes, topic: @topic %>
    <% end %>
  <% end %>
</div>