config/routes.rb
Rails.application.routes.draw do
  get '/plugs', to: 'plugs#index', as: :'plug'
  resources :topics do
    member do
      post 'downvote'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/users/:id', to: 'users#profile', as: 'user'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "topics#index"
  get 'search', to: 'search#index'
  get '/service-worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
end

app/views/shared/_confirm_modal.html.erb
<dialog id="turbo-confirm" class="bg-white shadow-lg rounded-lg p-6">
  <form method="dialog">
    <p class="text-lg font-semibold">Are you sure?</p>
    <div class="mt-4">
      <button value="cancel" class="bg-white border border-gray-300 hover:bg-gray-100 px-4 py-2 rounded-lg mr-1 font-medium">Cancel</button>
      <button value="confirm" class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium">Confirm</button>
    </div>
  </form>
</dialog>

app/views/shared/_empty_state.html.erb
<div class="flex flex-col items-center justify-center mt-8">
  <p class="text-lg text-gray-600 mb-4 text-center"><%= message %></p>
  <%= link_to new_topic_path, class: "rounded-lg flex items-center bg-black text-white px-4 py-2" do %>
    <% cache('bx-plus-circle.svg') do %>
      <%= image_tag "bx-plus-circle.svg", alt: "New", class: "w-5 mr-2", draggable: false %>
    <% end %>
    Create a Topic
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="py-2 px-3 mb-2
           <%= flash_type == 'alert' ? 'bg-red-100 text-red-500' : 'bg-green-100 text-green-500' %>
           font-medium rounded-lg inline-block"
    data-controller="auto-remove-message">
    <%= message %>
  </div>
<% end %>

app/views/shared/_form_error.html.erb
<% if topic.errors.include?(field) %>
  <% topic.errors.full_messages_for(field).each do |error| %>
   <p class="text-red-500 mt-2"><%= error %></p>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<%= render "shared/title" %>
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="Identify trending topics on X">
<meta name="turbo-refresh-method" content="morph">
<meta name="turbo-refresh-scroll" content="preserve">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />

<meta property="og:type" content="website">
<meta property="og:url" content="">
<meta property="og:title" content="Trending on X">
<meta property="og:image" content="">
<meta property="og:description" content="Identify trending topics on X">
<meta property="og:site_name" content="Trending on X">
<meta property="og:locale" content="en_US">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">

<meta name="twitter:card" content="Trending on X">
<meta name="twitter:url" content="">
<meta name="twitter:title" content="Content Title">
<meta name="twitter:description" content="Identify trending topics on X">
<meta name="twitter:image" content="">

app/views/shared/_loader.html.erb
<div class="flex items-center justify-center">
  <% cache("loading.svg") do %>
    <%= image_tag "loading.svg", alt: "Loading...", class: "w-10", draggable: false %>
  <% end %>
</div>

app/views/shared/_mobile_nav.html.erb
<nav
  class="bg-white shadow-md fixed top-0 w-full hidden z-1"
  data-navbar-target="content">
  <div class="flex justify-between">
    <div></div>
    <div data-action="click->navbar#close" class="hover:cursor-pointer px-5 pt-4">
      <% cache("bx-x-circle.svg") do %>
        <%= image_tag "bx-x-circle.svg", alt: "Close", class: "w-8", draggable: false %>
      <% end %>
    </div>
  </div>
  <ul class="text-right">
    <li class="py-2 px-5 text-lg"><%= link_to "Home", root_path %></li>
    <li class="py-2 px-5 text-lg"><%= link_to "Add topic", new_topic_path %></li>
    <li class="py-2 px-5 text-lg"><%= link_to "Plugs", plug_path %></li>
    <% if user_signed_in? %>
      <li class="py-2 px-5 text-lg">
        <%= link_to "Profile", user_path(current_user) %>
      </li>
      <li class="py-2 px-5 text-lg text-gray-500 bg-gray-50">
        <%= link_to "Sign out", destroy_user_session_path,
          class: "sign-out", data: { turbo_method: :delete } %>
      </li>
    <% else %>
      <li class="py-5 px-5 text-lg">
        <%= link_to "Sign in",  new_user_session_path,
          class: "py-2 px-3 bg-black text-white rounded-full" %>
      </li>
   <% end %>
  </ul>
</nav>

app/views/shared/_navbar.html.erb
<div data-controller="navbar" data-action="resize@window->navbar#closeOnBigScreen" class="navbar">
  <nav class="bg-white fixed top-0 w-full">
    <div class="container mx-auto flex items-center justify-between p-6">
      <div class="flex items-center">
        <%= link_to root_path do %>
          <p class="text-black text-2xl font-semibold hidden lg:flex py-2">
            Trending on X
          </p>
        <% end %>
      </div>

      <div class="flex items-center justify-center flex-grow">
        <%= render "search/form" %>
      </div>

      <div class="flex items-center space-x-6 ml-auto">
        <div class="hidden lg:flex">
          <%= link_to "Add topic", new_topic_path, class: "mr-5 py-2" %>
          <%= link_to "Plugs", plug_path, class: "mr-5 py-2" %>

          <% if user_signed_in? %>
            <%= render "shared/profile_dropdown" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "bg-black text-white rounded-full py-2 px-4" %>
          <% end %>
        </div>

        <div class="lg:hidden" role="button" data-action="click->navbar#toggle">
          <% cache("bx-menu.svg") do %>
            <%= image_tag "bx-menu.svg", alt: "Menu", class: "h-8 w-8", draggable:false %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  <%= render "shared/mobile_nav" %>
</div>

app/views/shared/_profile_dropdown.html.erb
<div data-controller="dropdown" class="relative inline-block text-left">
  <button
    data-action="click->dropdown#toggleDropdown"
    class="rounded-md border border-gray-400 px-4 py-2 text-sm font-medium focus:outline-none">
    <%= format_name(current_user) %>
  </button>

  <div
    data-dropdown-target="dropdown"
    class="hidden divide-y divide-gray-200 absolute right-0 mt-2 w-48 rounded-md border border-gray-300">
    <div class="px-4 py-3 text-gray-700 text-sm">
      Signed in as <span class="font-medium"><%= current_user.email %></span>
    </div>
    <div>
      <%= link_to "Profile", user_path(current_user),
        class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
      <%= link_to "Settings", edit_user_registration_path,
        method: :delete,
        class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
    </div>
    <div>
      <%= link_to "Sign out", destroy_user_session_path,
        data: { turbo_method: :delete },
        class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
    </div>
  </div>
</div>

app/views/shared/_scroll_to_top.html.erb
<div
  data-controller="scroll-to-top"
  class="scroll-to-top"
  data-action="click->scroll-to-top#scrollToTop"
  data-scroll-to-top-target="backToTop"
>
  <% cache('bx-up-arrow-alt.svg') do %>
    <%= image_tag "bx-up-arrow-alt.svg", alt: "Scroll to top", class: "w-10", draggable: false %>
  <% end %>
</div>

app/views/shared/_title.html.erb
<title>
  <%= content_for?(:title) ? yield(:title) : "Trending on X - Identify trending topics on X" %>
</title>

app/views/shared/_topic_count.html.erb
<% cache ['topics_count', topics] do %>
  <%= "#{format_count(topics.length)} #{'Topic'.pluralize(topics.length)}" %>
<% end %>